#!/bin/bash
#
# Build (and publish?) libapach2-mod-wsgi debian package
#
# Run this script from the grandparent directory like:
#   cd .. && ./mod-wsgi/build

MOD_WSGI_VERSION=${MOD_WSGI_VERSION:-4.6.4}

function import_keys() {
    if [ ! -e mod-wsgi/private.key ]; then
        echo "missing private.key file!"
        exit 1
    fi

    gpg --allow-secret-key-import --import mod-wsgi/private.key
}

function download() {
    curl -L https://github.com/GrahamDumpleton/mod_wsgi/archive/${MOD_WSGI_VERSION}.tar.gz -o mod-wsgi_${MOD_WSGI_VERSION}.orig.tar.gz
    tar -xzf mod-wsgi_${MOD_WSGI_VERSION}.orig.tar.gz
    mv mod_wsgi-${MOD_WSGI_VERSION} mod-wsgi-${MOD_WSGI_VERSION}
}


function build() {
    pushd mod-wsgi-${MOD_WSGI_VERSION}
    mkdir debian
    cp -r ../mod-wsgi/debian/* debian/

    # Create changelog entry for this version
    dch --create -M --package mod-wsgi -v ${MOD_WSGI_VERSION} -D trusty -u low "Automated Build"

    dpkg-buildpackage -us -uc
    popd
}

function create_repo() {
    reprepro --basedir debian includedeb trusty libapache2-mod-wsgi_${MOD_WSGI_VERSION}_amd64.deb
}

# Main
import_keys
download
build
create_repo
